.TH "BulletController" 3 "Thu Feb 25 2021" "Version 0.1" "Asteroid QMOBI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BulletController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Контроллер пули 
.PP
Definition at line 28 of file BulletController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Asteroid QMOBI from the source code\&.
