.TH "CanvasUIManager" 3 "Thu Feb 25 2021" "Version 0.1" "Asteroid QMOBI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanvasUIManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBTextScore\fP"
.br
.ti -1c
.RI "GameObject \fBLivesParent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Менеджер UI канваса (при загрузке отключает CenterChat (Text компонент на объекте)) 
.PP
\fBParameters\fP
.RS 4
\fITextScore\fP Text текстовое поле для игровых очков 
.br
\fICenterChat\fP Text текстовое поле в центре экрана для чата с игроком 
.br
\fILivesParent\fP GameObject родитель для отображения колличества жизней(UI) 
.RE
.PP

.PP
Definition at line 12 of file CanvasUIManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Asteroid QMOBI from the source code\&.
