.TH "CanvasGameManager" 3 "Thu Feb 25 2021" "Version 0.1" "Asteroid QMOBI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanvasGameManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBBulletsParent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Менеджер Game канваса 
.PP
\fBParameters\fP
.RS 4
\fIBulletsParent\fP GameObject родитель для пуль 
.br
\fIEnemyParent\fP GameObject родитель для врагов 
.br
\fIParticleParent\fP GameObject родитель для партиклов 
.RE
.PP

.PP
Definition at line 10 of file CanvasGameManager\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Asteroid QMOBI from the source code\&.
