.TH "PlayerController" 3 "Thu Feb 25 2021" "Version 0.1" "Asteroid QMOBI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Контроллер Игрока 
.PP
\fBParameters\fP
.RS 4
\fIBulletsStartPoint\fP GameObject сериализованное приватное поле - Стартовая позиция для пули 
.br
\fIBulletPrefab\fP GameObject сериализованное приватное поле - Префаб пули
.br
\fI_shipSpeed\fP float сериализованное приватное поле - скорость игрока 
.br
\fI_bulletSpeed\fP float сериализованное приватное поле - скорость пули
.br
\fI_gameManager\fP \fBGameManager\fP менеджер игры 
.br
\fI_rb\fP Rigidbody2D компонент rigidbody2d игрока 
.br
\fI_particle\fP ParticleSystem партиклы игрока(огонь, выходящий из нижней части корабля)
.br
\fI_IsCenterChatActive\fP bool булиновка, определяющая состояние центрального чата 
.br
\fI_IsSuperMode\fP bool булиновка, определяющая находится ли игрок в состояние неуязвимости(Супер мод) 
.RE
.PP

.PP
Definition at line 21 of file PlayerController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Asteroid QMOBI from the source code\&.
